apiVersion: v1
kind: Service
metadata: { name: web, namespace: app }
spec:
  selector: { app: web }
  ports: [{ name: http, port: 8000, targetPort: 8000 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: web, namespace: app }
spec:
  replicas: 1
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      initContainers:
        - name: migrate
          image: localhost:5001/djapp:dev
          env:
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: db, key: DB_NAME } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: db, key: DB_PASSWORD } }
            - name: DB_HOST
              value: postgres.app.svc.cluster.local
            - name: DB_PORT
              value: "5432"
          command: ["python", "manage.py", "migrate", "--noinput"]
      containers:
        - name: web
          image: localhost:5001/djapp:1.0.2
          ports: [{ containerPort: 8000, name: http }]
          env:
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: db, key: DB_NAME } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: db, key: DB_PASSWORD } }
            - name: DB_HOST
              value: postgres.app.svc.cluster.local
            - name: DB_PORT
              value: "5432"
          readinessProbe:
            httpGet: { path: /readiness, port: http }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /liveness, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
